2024-02-09 11:06:31,199 INFO    StreamThr :482362 [internal.py:wandb_internal():86] W&B internal server running at pid: 482362, started at: 2024-02-09 11:06:31.198566
2024-02-09 11:06:31,199 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status
2024-02-09 11:06:31,204 INFO    WriterThread:482362 [datastore.py:open_for_write():85] open: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/run-u2royrke.wandb
2024-02-09 11:06:31,204 DEBUG   SenderThread:482362 [sender.py:send():382] send: header
2024-02-09 11:06:31,211 DEBUG   SenderThread:482362 [sender.py:send():382] send: run
2024-02-09 11:06:31,742 INFO    SenderThread:482362 [dir_watcher.py:__init__():211] watching files in: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files
2024-02-09 11:06:31,742 INFO    SenderThread:482362 [sender.py:_start_run_threads():1136] run started: u2royrke with start time 1707473191.198497
2024-02-09 11:06:31,751 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: check_version
2024-02-09 11:06:31,752 DEBUG   SenderThread:482362 [sender.py:send_request():409] send_request: check_version
2024-02-09 11:06:31,893 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: run_start
2024-02-09 11:06:31,899 DEBUG   HandlerThread:482362 [system_info.py:__init__():32] System info init
2024-02-09 11:06:31,899 DEBUG   HandlerThread:482362 [system_info.py:__init__():47] System info init done
2024-02-09 11:06:31,899 INFO    HandlerThread:482362 [system_monitor.py:start():194] Starting system monitor
2024-02-09 11:06:31,899 INFO    SystemMonitor:482362 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-09 11:06:31,899 INFO    HandlerThread:482362 [system_monitor.py:probe():214] Collecting system info
2024-02-09 11:06:31,899 INFO    SystemMonitor:482362 [interfaces.py:start():190] Started cpu monitoring
2024-02-09 11:06:31,900 INFO    SystemMonitor:482362 [interfaces.py:start():190] Started disk monitoring
2024-02-09 11:06:31,900 INFO    SystemMonitor:482362 [interfaces.py:start():190] Started gpu monitoring
2024-02-09 11:06:31,901 INFO    SystemMonitor:482362 [interfaces.py:start():190] Started memory monitoring
2024-02-09 11:06:31,901 INFO    SystemMonitor:482362 [interfaces.py:start():190] Started network monitoring
2024-02-09 11:06:31,964 DEBUG   HandlerThread:482362 [system_info.py:probe():196] Probing system
2024-02-09 11:06:31,966 DEBUG   HandlerThread:482362 [system_info.py:_probe_git():181] Probing git
2024-02-09 11:06:31,975 DEBUG   HandlerThread:482362 [system_info.py:_probe_git():189] Probing git done
2024-02-09 11:06:31,975 DEBUG   HandlerThread:482362 [system_info.py:probe():244] Probing system done
2024-02-09 11:06:31,975 DEBUG   HandlerThread:482362 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.31', 'python': '3.11.5', 'heartbeatAt': '2024-02-09T10:06:31.964156', 'startedAt': '2024-02-09T10:06:31.191044', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py', 'codePathLocal': 'Kod/train.py', 'codePath': 'Kod/train.py', 'git': {'remote': 'https://github.com/marcin-jankowskii/noisy_labels.git', 'commit': '9b75e31a2af2c417c6e693874fb07e489aeec1f0'}, 'email': 'marcinjankowskirep@gmail.com', 'root': '/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels', 'host': 'cal3141-X570S-AERO-G', 'username': 'cal314-1', 'executable': '/home/cal314-1/miniconda3/envs/marcin/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2.6029375, 'min': 2200.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 2.8, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 3.695, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 4.191, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 2.2, 'min': 2200.0, 'max': 3400.0}, {'current': 3.4, 'min': 2200.0, 'max': 3400.0}], 'disk': {'/': {'total': 425.5165710449219, 'used': 171.70106887817383}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 125.7255630493164}}
2024-02-09 11:06:31,975 INFO    HandlerThread:482362 [system_monitor.py:probe():224] Finished collecting system info
2024-02-09 11:06:31,975 INFO    HandlerThread:482362 [system_monitor.py:probe():227] Publishing system info
2024-02-09 11:06:31,975 DEBUG   HandlerThread:482362 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-02-09 11:06:31,975 DEBUG   HandlerThread:482362 [system_info.py:_save_pip():68] Saving pip packages done
2024-02-09 11:06:31,976 DEBUG   HandlerThread:482362 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-02-09 11:06:32,743 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_created():271] file/dir created: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/requirements.txt
2024-02-09 11:06:32,743 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_created():271] file/dir created: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/conda-environment.yaml
2024-02-09 11:06:34,300 DEBUG   HandlerThread:482362 [system_info.py:_save_conda():87] Saving conda packages done
2024-02-09 11:06:34,300 INFO    HandlerThread:482362 [system_monitor.py:probe():229] Finished publishing system info
2024-02-09 11:06:34,303 DEBUG   SenderThread:482362 [sender.py:send():382] send: files
2024-02-09 11:06:34,303 INFO    SenderThread:482362 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-02-09 11:06:34,308 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: stop_status
2024-02-09 11:06:34,308 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-09 11:06:34,308 DEBUG   SenderThread:482362 [sender.py:send_request():409] send_request: stop_status
2024-02-09 11:06:34,743 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_modified():288] file/dir modified: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/conda-environment.yaml
2024-02-09 11:06:34,743 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_created():271] file/dir created: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/wandb-metadata.json
2024-02-09 11:06:34,991 DEBUG   SenderThread:482362 [sender.py:send():382] send: telemetry
2024-02-09 11:06:34,991 DEBUG   SenderThread:482362 [sender.py:send():382] send: telemetry
2024-02-09 11:06:34,992 DEBUG   SenderThread:482362 [sender.py:send():382] send: run
2024-02-09 11:06:35,457 INFO    SenderThread:482362 [sender.py:send_run():1010] updated run: u2royrke
2024-02-09 11:06:35,744 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_modified():288] file/dir modified: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/config.yaml
2024-02-09 11:06:35,744 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_created():271] file/dir created: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/output.log
2024-02-09 11:06:36,079 INFO    wandb-upload_0:482362 [upload_job.py:push():131] Uploaded file /tmp/tmpg_38op5xwandb/imkx6hz6-wandb-metadata.json
2024-02-09 11:06:36,458 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:06:37,745 INFO    Thread-12 :482362 [dir_watcher.py:_on_file_modified():288] file/dir modified: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/files/output.log
2024-02-09 11:06:41,458 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:06:46,459 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:06:49,308 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: stop_status
2024-02-09 11:06:49,308 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-09 11:06:49,308 DEBUG   SenderThread:482362 [sender.py:send_request():409] send_request: stop_status
2024-02-09 11:06:51,549 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:06:56,550 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:07:01,552 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: status_report
2024-02-09 11:07:01,795 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:01,795 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:07:04,350 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: stop_status
2024-02-09 11:07:04,350 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-09 11:07:05,237 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:05,237 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:07:07,937 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:07,937 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:07:07,937 INFO    SenderThread:482362 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-02-09 11:07:09,308 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: keepalive
2024-02-09 11:07:12,547 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:12,547 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:07:14,309 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: keepalive
2024-02-09 11:07:19,651 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: poll_exit
2024-02-09 11:07:20,962 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:20,963 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:07:24,652 DEBUG   HandlerThread:482362 [handler.py:handle_request():146] handle_request: keepalive
2024-02-09 11:07:27,916 INFO    cpu       :482362 [interfaces.py:monitor():140] Process cpu has exited.
2024-02-09 11:07:27,916 INFO    memory    :482362 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-02-09 11:07:27,916 DEBUG   SystemMonitor:482362 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-09 11:07:27,917 DEBUG   SystemMonitor:482362 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-09 11:07:27,917 DEBUG   SystemMonitor:482362 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-09 11:07:28,204 WARNING StreamThr :482362 [internal.py:is_dead():414] Internal process exiting, parent pid 482269 disappeared
2024-02-09 11:07:28,204 ERROR   StreamThr :482362 [internal.py:wandb_internal():152] Internal process shutdown.
2024-02-09 11:07:28,918 INFO    HandlerThread:482362 [handler.py:finish():866] shutting down handler
2024-02-09 11:07:28,918 INFO    WriterThread:482362 [datastore.py:close():294] close: /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240209_110631-u2royrke/run-u2royrke.wandb
2024-02-09 11:07:28,918 INFO    HandlerThread:482362 [system_monitor.py:finish():203] Stopping system monitor
2024-02-09 11:07:28,918 INFO    HandlerThread:482362 [interfaces.py:finish():202] Joined cpu monitor
2024-02-09 11:07:28,919 INFO    HandlerThread:482362 [interfaces.py:finish():202] Joined disk monitor
2024-02-09 11:07:28,919 INFO    HandlerThread:482362 [interfaces.py:finish():202] Joined gpu monitor
2024-02-09 11:07:28,919 INFO    HandlerThread:482362 [interfaces.py:finish():202] Joined memory monitor
2024-02-09 11:07:28,919 INFO    HandlerThread:482362 [interfaces.py:finish():202] Joined network monitor
2024-02-09 11:07:37,431 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:07:37,431 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:08:11,956 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:08:11,956 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:09:18,758 ERROR   SenderThread:482362 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-09 11:09:18,758 ERROR   SenderThread:482362 [internal_api.py:execute():374] {"errors":[{"message":"run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-09 11:09:18,758 ERROR   StreamThr :482362 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2212, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 540, in debounce
    self._maybe_update_config(always=final)
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 517, in _maybe_update_config
    self._debounce_config()
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 546, in _debounce_config
    self._api.upsert_run(
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run segsperm/noisy_labels/u2royrke was previously created and deleted; try a new run name (Error 409: Conflict)
