2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Configure stats pid to 339280
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Loading settings from /home/cal314-1/.config/wandb/settings
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Loading settings from /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/settings
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Kod/inference.py', 'program_abspath': '/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/inference.py', 'program': '/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/inference.py'}
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_init.py:_log_setup():526] Logging user logs to /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240301_145941-mpn2vhfj/logs/debug.log
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_init.py:_log_setup():527] Logging internal logs to /media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/wandb/run-20240301_145941-mpn2vhfj/logs/debug-internal.log
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_init.py:init():566] calling init triggers
2024-03-01 14:59:41,716 INFO    MainThread:339280 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': 'smpUNet++', 'batch_size': 1, 'annotator': 2, 'place': 'lab', 'mode': 'normal'}
2024-03-01 14:59:41,717 INFO    MainThread:339280 [wandb_init.py:init():616] starting backend
2024-03-01 14:59:41,717 INFO    MainThread:339280 [wandb_init.py:init():620] setting up manager
2024-03-01 14:59:41,721 INFO    MainThread:339280 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-01 14:59:41,722 INFO    MainThread:339280 [wandb_init.py:init():628] backend started and connected
2024-03-01 14:59:41,728 INFO    MainThread:339280 [wandb_init.py:init():720] updated telemetry
2024-03-01 14:59:41,736 INFO    MainThread:339280 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-01 14:59:43,507 INFO    MainThread:339280 [wandb_run.py:_on_init():2262] communicating current version
2024-03-01 14:59:43,661 INFO    MainThread:339280 [wandb_run.py:_on_init():2271] got version response 
2024-03-01 14:59:43,661 INFO    MainThread:339280 [wandb_init.py:init():804] starting run threads in backend
2024-03-01 14:59:45,591 INFO    MainThread:339280 [wandb_run.py:_console_start():2241] atexit reg
2024-03-01 14:59:45,591 INFO    MainThread:339280 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-01 14:59:45,592 INFO    MainThread:339280 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-01 14:59:45,592 INFO    MainThread:339280 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-01 14:59:45,592 INFO    MainThread:339280 [wandb_init.py:init():847] run started, returning control to user process
2024-03-01 15:00:05,288 ERROR   MainThread:339280 [util.py:get_module():267] Error importing optional module moviepy.editor
Traceback (most recent call last):
  File "/home/cal314-1/miniconda3/envs/marcinv2/lib/python3.11/site-packages/wandb/util.py", line 233, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'moviepy.editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cal314-1/miniconda3/envs/marcinv2/lib/python3.11/site-packages/wandb/util.py", line 262, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcinv2/lib/python3.11/site-packages/wandb/util.py", line 235, in import_module_lazy
    spec = importlib.util.find_spec(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 94, in find_spec
ModuleNotFoundError: No module named 'moviepy'
2024-03-01 15:00:11,911 WARNING MsgRouterThr:339280 [router.py:message_loop():77] message_loop has been closed
